In [1]:
from qiskit import QuantumCircuit
from qiskit.providers.aer import AerSimulator

In [2]:
sim = AerSimulator()

## Exploring Qubits - Hadamard Gates

In [3]:
qc = QuantumCircuit(1,1)
qc.h(0)
qc.measure([0],[0])
display(qc.draw())


job = sim.run(qc)
result = job.result()
result.get_counts()

┌───┐┌─┐
  q: ┤ H ├┤M├
     └───┘└╥┘
c: 1/══════╩═
           0

{'0': 477, '1': 547}

In [4]:
qc = QuantumCircuit(1,1)
qc.x(0)
qc.h(0)
qc.measure([0],[0])
display(qc.draw())


job = sim.run(qc)
result = job.result()
result.get_counts()

┌───┐┌───┐┌─┐
  q: ┤ X ├┤ H ├┤M├
     └───┘└───┘└╥┘
c: 1/═══════════╩═
                0

{'1': 511, '0': 513}

In [5]:
qc = QuantumCircuit(1,1)
qc.h(0)
qc.h(0)
qc.measure([0],[0])
display(qc.draw())


job = sim.run(qc)
result = job.result()
result.get_counts()

┌───┐┌───┐┌─┐
  q: ┤ H ├┤ H ├┤M├
     └───┘└───┘└╥┘
c: 1/═══════════╩═
                0

{'0': 1024}

In [6]:
qc = QuantumCircuit(1,1)
qc.x(0)
qc.h(0)
qc.h(0)
qc.measure([0],[0])
display(qc.draw())


job = sim.run(qc)
result = job.result()
result.get_counts()

┌───┐┌───┐┌───┐┌─┐
  q: ┤ X ├┤ H ├┤ H ├┤M├
     └───┘└───┘└───┘└╥┘
c: 1/════════════════╩═
                     0

{'1': 1024}

## Quantum Operations

The CNOT operation can be represented as 4x4 matrix.

$$
\text{CNOT} = \begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0
\end{pmatrix}
$$

For example, consider the addition of $00 + 01 = 01$.

It is same as
$$
\text{CNOT} \begin{pmatrix}0 \\ 0 \\ 0 \\ 1\end{pmatrix} = \begin{pmatrix}0 \\ 1 \\ 0 \\ 0\end{pmatrix}
$$

In [7]:
import numpy as np

cnot = np.matrix("1 0 0 0;0 0 0 1;0 0 1 0;0 1 0 0")

In [8]:
cnot @ np.array([0,0,1,0])

matrix([[0, 0, 1, 0]])

In [9]:
cnot @ np.array([1,0,0,0])

matrix([[1, 0, 0, 0]])

In [10]:
cnot @ np.array([0,1,0,0])

matrix([[0, 0, 0, 1]])

In [11]:
cnot.T @ cnot # Unitary

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

The H-gate is represented by 2x2 matrix :

$$
H = \sqrt{\frac{1}{2}} \begin{pmatrix}
1 & 1 \\
1 & -1
\end{pmatrix}
$$

$$
\begin{gathered}
H|0\rangle = \sqrt{\frac{1}{2}} \begin{pmatrix}
1 & 1 \\
1 & -1
\end{pmatrix} \begin{pmatrix} 1 \\ 0 \end{pmatrix}
= \sqrt{\frac{1}{2}}\begin{pmatrix} 1 \\ 1 \end{pmatrix} \\
H|1\rangle = \sqrt{\frac{1}{2}} \begin{pmatrix}
1 & 1 \\
1 & -1
\end{pmatrix} \begin{pmatrix} 0 \\ 1 \end{pmatrix}
= \sqrt{\frac{1}{2}}\begin{pmatrix} 1 \\ -1 \end{pmatrix} 
\end{gathered}
$$

In [12]:
H = np.matrix("1 1;1 -1") * np.sqrt(1/2)

H.T @ H # Unitary

matrix([[1.00000000e+00, 4.26642159e-17],
        [4.26642159e-17, 1.00000000e+00]])